[[t_menu]]
  Path = "/dashboard"
  Title = "面板"
  Icon = "link"
  LeftEdge = 1
  RightEdge = 2
  Depth = 1
  SeqNo = 1
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "/permission"
  Title = "权限"
  Icon = "link"
  LeftEdge = 3
  RightEdge = 6
  Depth = 1
  SeqNo = 2
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "role"
  Title = "角色权限"
  LeftEdge = 4
  RightEdge = 5
  Depth = 2
  SeqNo = 1
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "/table"
  Title = "Table"
  Icon = "link"
  LeftEdge = 7
  RightEdge = 10
  Depth = 1
  SeqNo = 3
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "complex-table"
  Title = "复杂Table"
  LeftEdge = 8
  RightEdge = 9
  Depth = 2
  SeqNo = 1
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "inline-edit-table"
  Title = "内联编辑"
  LeftEdge = 10
  RightEdge = 11
  Depth = 2
  SeqNo = 2
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "/excel"
  Title = "Excel"
  Icon = "link"
  LeftEdge = 13
  RightEdge = 16
  Depth = 1
  SeqNo = 4
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "export-selected-excel"
  Title = "选择导出"
  LeftEdge = 14
  RightEdge = 15
  Depth = 2
  SeqNo = 1
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "upload-excel"
  Title = "上传Excel"
  LeftEdge = 16
  RightEdge = 17
  Depth = 2
  SeqNo = 2
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "/theme/index"
  Title = "主题"
  Icon = "link"
  LeftEdge = 19
  RightEdge = 20
  Depth = 1
  SeqNo = 5
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "/error/404"
  Title = "404错误"
  Icon = "link"
  LeftEdge = 21
  RightEdge = 22
  Depth = 1
  SeqNo = 6
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_menu]]
  Path = "https://cn.vuejs.org/"
  Title = "外部链接"
  Icon = "link"
  LeftEdge = 23
  RightEdge = 24
  Depth = 1
  SeqNo = 7
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_role]]
  Name = "superuser"
  Remark = "基本用户，只能看到面板页。"
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_role]]
  Name = "member"
  Remark = "基本用户，只能看到面板页。"
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_role]]
  Name = "visitor"
  Remark = "基本用户，只能看到面板页。"
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_user_role]]
  UserUID = "6kff25twcor76222"
  RoleName = "superuser"

[[t_user_role]]
  UserUID = "6kff25u4cor76223"
  RoleName = "member"

[[t_user]]
  UID = "6kff25twcor76222"
  Username = "admin"
  Password = "09e8ff53$x1KWXASXqGRzA7YwipQhibg/0LMtkoU39VfW8EYtxAI="
  Realname = "管理员"
  PrinGid = ""
  Avatar = "/avatars/avatar-admin.jpg"
  Introduction = "不受限的超管账号。"
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z

[[t_user]]
  UID = "6kff25u4cor76223"
  Username = "demo"
  Password = "acfd1f8b$o6ySKi7yaMmZrKIaT4O/oGUoei6n/xKOXik4PtXuvwk="
  Realname = "演示用户"
  PrinGid = ""
  Avatar = "/avatars/avatar-demo.jpg"
  Introduction = "演示和测试账号。"
  CreatedAt = 2019-12-01T11:12:00Z
  UpdatedAt = 2019-12-01T11:12:00Z
