[application]
    debug        = true
    plural_table = false       #表名是否使用复数
    output_dir   = "./models"  #models输出目录

[connections.default]
    driver   = "mysql"         #数据库类型
    host     = "127.0.0.1"
    port     = 3306
    username = "root"
    password = ""
    database = "test"
    prefix   = "t_"            #表名前缀
    options  = { charset="utf8mb4" }

[connections.sqlite]
    driver   = "sqlite"
    database = "./test.db"

[modelRules._]
    created_at = { type="time.Time", comment="创建时间" }
    updated_at = { type="time.Time", comment="更新时间" }
    deleted_at = { type="*time.Time", comment="删除时间" }

[modelRules.t_user]
    password   = { json="-", comment="密码" }
