[application]
    output_dir   = "./models"  #models输出目录
    table_prefix = "t_"        #表名前缀
    plural_table = true      #表名是否使用复数

[connections.default]
    driver   = "mysql"         #数据库类型
    host     = "127.0.0.1"
    port     = 3306
    username = "root"
    password = ""
    database = "test"
    options  = { charset="utf8mb4" }

[connections.sqlite]
    driver   = "sqlite"
    database = "./test.db"

[modelRules._]
    created_at = { type="time.Time", json="CreatedAt", comment="创建时间" }
    updated_at = { type="time.Time", json="UpdatedAt", comment="更新时间" }
    deleted_at = { type="*time.Time", json="DeletedAt", comment="删除时间" }

[modelRules.t_users]
    username = { name="UserName", json="username" }
    password = { name="PassWord", json="password" }